package com.vcyber.tspplatform.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2015-09-25T08:18:19.919+08:00
 * Generated source version: 3.0.6
 * 
 */
@WebServiceClient(name = "TSPCCService", 
                  wsdlLocation = "http://59.46.215.194:5355/TSPCCService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class TSPCCService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "TSPCCService");
    public final static QName TSPCCServiceSoap = new QName("http://tempuri.org/", "TSPCCServiceSoap");
    public final static QName TSPCCServiceSoap12 = new QName("http://tempuri.org/", "TSPCCServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://59.46.215.194:5355/TSPCCService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TSPCCService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://59.46.215.194:5355/TSPCCService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TSPCCService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TSPCCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TSPCCService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TSPCCServiceSoap
     */
    @WebEndpoint(name = "TSPCCServiceSoap")
    public TSPCCServiceSoap getTSPCCServiceSoap() {
        return super.getPort(TSPCCServiceSoap, TSPCCServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TSPCCServiceSoap
     */
    @WebEndpoint(name = "TSPCCServiceSoap")
    public TSPCCServiceSoap getTSPCCServiceSoap(WebServiceFeature... features) {
        return super.getPort(TSPCCServiceSoap, TSPCCServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns TSPCCServiceSoap
     */
    @WebEndpoint(name = "TSPCCServiceSoap12")
    public TSPCCServiceSoap getTSPCCServiceSoap12() {
        return super.getPort(TSPCCServiceSoap12, TSPCCServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TSPCCServiceSoap
     */
    @WebEndpoint(name = "TSPCCServiceSoap12")
    public TSPCCServiceSoap getTSPCCServiceSoap12(WebServiceFeature... features) {
        return super.getPort(TSPCCServiceSoap12, TSPCCServiceSoap.class, features);
    }

}
