package com.vcyber.tspplatform.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2015-09-25T08:18:19.909+08:00
 * Generated source version: 3.0.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TSPCCServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TSPCCServiceSoap {

    @WebResult(name = "TSPCCTBoxRingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TSPCCTBoxRing", targetNamespace = "http://tempuri.org/", className = "com.vcyber.tspplatform.service.client.TSPCCTBoxRing")
    @WebMethod(operationName = "TSPCCTBoxRing", action = "http://tempuri.org/TSPCCTBoxRing")
    @ResponseWrapper(localName = "TSPCCTBoxRingResponse", targetNamespace = "http://tempuri.org/", className = "com.vcyber.tspplatform.service.client.TSPCCTBoxRingResponse")
    public java.lang.String tspcctBoxRing(
        @WebParam(name = "JsonStr", targetNamespace = "http://tempuri.org/")
        java.lang.String jsonStr
    );
}
